package io.nativeplanet.launcher.data.stub

import io.nativeplanet.launcher.domain.NativePlanetClient
import io.nativeplanet.launcher.domain.model.*
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import java.time.Instant
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class StubNativePlanetClient @Inject constructor() : NativePlanetClient {

    private val _runtimeStatus = MutableStateFlow(
        RuntimeStatus(
            state = RuntimeState.STOPPED,
            shipName = "~lislys-hinnyt-dalhec-banler",
            bootMode = BootMode.MOON,
            pid = null,
            uptimeMs = null,
            lastStartTime = null,
            lastStopTime = Instant.now().minusSeconds(3600),
            lastError = null,
            exitCode = null
        )
    )

    private val _networkStatus = MutableStateFlow(
        NetworkStatus(
            type = NetworkType.WIFI,
            interfaceName = "wlan0",
            stackedInterfaceName = null,
            validated = true,
            dnsServers = listOf("10.0.0.1", "8.8.8.8"),
            nat64Prefix = null,
            timestampMs = System.currentTimeMillis(),
            resolverAvailable = true,
            resolverContents = """
                # Generated by NativePlanet Controller
                # Network: WIFI via wlan0
                nameserver 10.0.0.1
                nameserver 8.8.8.8
            """.trimIndent()
        )
    )

    private val _bootPackageStatus = MutableStateFlow(
        BootPackageStatus(
            exists = true,
            valid = true,
            packageVersion = 1,
            bootMode = BootMode.MOON,
            ship = "~lislys-hinnyt-dalhec-banler",
            parent = "~dalhec-banler",
            pierPath = "/data/nativeplanet/ships/lislys-hinnyt-dalhec-banler",
            pillPath = "/system_ext/etc/nativeplanet/satellite.pill",
            pierExists = true,
            pillExists = true,
            keyFileExists = true,
            validationErrors = emptyList()
        )
    )

    private val _diagnostics = MutableStateFlow(
        DiagnosticsSummary(
            controllerLogs = listOf(
                LogLine(Instant.now().minusSeconds(120), LogLevel.INFO, "Controller service starting"),
                LogLine(Instant.now().minusSeconds(60), LogLevel.INFO, "Network state: WIFI via wlan0, validated=true"),
                LogLine(Instant.now().minusSeconds(30), LogLevel.INFO, "Wrote resolv.conf with 2 DNS servers")
            ),
            launcherLogs = listOf(
                LogLine(Instant.now().minusSeconds(10), LogLevel.INFO, "BootPackage loaded: ship=~lislys-hinnyt-dalhec-banler")
            ),
            recentErrors = emptyList(),
            resolverContents = """
                # Generated by NativePlanet Controller
                # Network: WIFI via wlan0
                nameserver 10.0.0.1
                nameserver 8.8.8.8
            """.trimIndent(),
            networkStateRaw = """{"networkType":"WIFI","interfaceName":"wlan0","validated":true}"""
        )
    )

    override fun observeRuntimeStatus(): Flow<RuntimeStatus> = _runtimeStatus.asStateFlow()
    override fun observeNetworkStatus(): Flow<NetworkStatus> = _networkStatus.asStateFlow()
    override fun observeBootPackageStatus(): Flow<BootPackageStatus> = _bootPackageStatus.asStateFlow()
    override fun observeDiagnostics(): Flow<DiagnosticsSummary> = _diagnostics.asStateFlow()

    override suspend fun startRuntime(): ControlResult {
        val current = _runtimeStatus.value
        if (current.state == RuntimeState.RUNNING) {
            return ControlResult.AlreadyInState(RuntimeState.RUNNING)
        }

        _runtimeStatus.value = current.copy(state = RuntimeState.STARTING)
        delay(2000)
        _runtimeStatus.value = current.copy(
            state = RuntimeState.RUNNING,
            pid = 12345,
            uptimeMs = 0,
            lastStartTime = Instant.now()
        )
        return ControlResult.Success
    }

    override suspend fun stopRuntime(): ControlResult {
        val current = _runtimeStatus.value
        if (current.state == RuntimeState.STOPPED) {
            return ControlResult.AlreadyInState(RuntimeState.STOPPED)
        }

        _runtimeStatus.value = current.copy(state = RuntimeState.STOPPING)
        delay(1000)
        _runtimeStatus.value = current.copy(
            state = RuntimeState.STOPPED,
            pid = null,
            uptimeMs = null,
            lastStopTime = Instant.now()
        )
        return ControlResult.Success
    }

    override suspend fun restartRuntime(): ControlResult {
        stopRuntime()
        delay(500)
        return startRuntime()
    }

    override suspend fun provisionMoon(
        shipName: String,
        parentName: String,
        keyMaterial: String
    ): ControlResult {
        val normalizedShip = if (shipName.startsWith("~")) shipName else "~$shipName"
        val normalizedParent = if (parentName.startsWith("~")) parentName else "~$parentName"
        _bootPackageStatus.value = _bootPackageStatus.value.copy(
            exists = true,
            valid = true,
            ship = normalizedShip,
            parent = normalizedParent,
            bootMode = BootMode.MOON,
            keyFileExists = keyMaterial.isNotBlank(),
            pierExists = false,
            validationErrors = emptyList()
        )
        _runtimeStatus.value = _runtimeStatus.value.copy(
            state = RuntimeState.STARTING,
            shipName = normalizedShip,
            bootMode = BootMode.MOON
        )
        delay(1500)
        _runtimeStatus.value = _runtimeStatus.value.copy(
            state = RuntimeState.RUNNING,
            shipName = normalizedShip,
            bootMode = BootMode.MOON,
            lastStartTime = Instant.now()
        )
        return ControlResult.Success
    }

    override suspend fun pairWithPlanet(hostUrl: String, accessCode: String): ControlResult {
        delay(500)
        return ControlResult.Failed(
            "PARENT_PAIRING_UNAVAILABLE",
            "Parent pairing is not available in this build"
        )
    }
}
